// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GeolocationController from "./geolocation_controller"
application.register("geolocation", GeolocationController)

import TypeController from "./type_controller"
application.register("type", TypeController)

import PartageController from "./partage_controller"
application.register("partage", PartageController)