approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  "stimulus-use@*":
    peerDependenciesMeta:
      hotkeys-js:
        optional: true
